// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBv4UhQ4FXbXk9rZZIL4hMI2LAEhTY2eKc',
    appId: '1:491949219028:web:7e6462bc167511a0c26f41',
    messagingSenderId: '491949219028',
    projectId: 'aura-1153e',
    authDomain: 'aura-1153e.firebaseapp.com',
    storageBucket: 'aura-1153e.appspot.com',
    measurementId: 'G-SH8Y8D01R4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAITa_lWgFLS_lPUWUF4i2MdMlisULf2bw',
    appId: '1:491949219028:android:183f50798a079a72c26f41',
    messagingSenderId: '491949219028',
    projectId: 'aura-1153e',
    storageBucket: 'aura-1153e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDxybmEo4SQbQsCiLRpMlcnl3_KjUHOeoE',
    appId: '1:491949219028:ios:43893a232f79557dc26f41',
    messagingSenderId: '491949219028',
    projectId: 'aura-1153e',
    storageBucket: 'aura-1153e.appspot.com',
    iosClientId: '491949219028-789p5dvutnhcpvmnlffpc2rc8uhcmt32.apps.googleusercontent.com',
    iosBundleId: 'com.example.firephone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDxybmEo4SQbQsCiLRpMlcnl3_KjUHOeoE',
    appId: '1:491949219028:ios:4716c8a9031f7059c26f41',
    messagingSenderId: '491949219028',
    projectId: 'aura-1153e',
    storageBucket: 'aura-1153e.appspot.com',
    iosClientId: '491949219028-1jioq9u163e3iadgpk901uqs367s74hc.apps.googleusercontent.com',
    iosBundleId: 'com.example.firephone.RunnerTests',
  );
}
